
spring:
    datasource:
        url: jdbc:h2:mem:bankdb
        driverClassName: org.h2.Driver
        username: sa
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    application:
     name : Bank Systemspring
    h2:
    console:
      enabled: true
      path: /h2-console


server:
    port: 8028

